/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "#080a10",
        surface: "#0f1117",
        primary: "#cabeff",
        "on-primary": "#1c1148",
        "primary-text": "#f0eff0",
        "secondary-text": "#8b8fa8",
        outline: "#33343c",
        "card-bg": "#0f1117",
        "card-hover": "#161b27",
        "on-surface": "#e2e2eb",
        "on-surface-variant": "#a1a1aa",
        "border-subtle": "rgba(255, 255, 255, 0.07)",
        border: "rgba(255, 255, 255, 0.07)",
        tertiary: "#55ddab",
        "surface-container": "#1d1f26",
        "surface-container-lowest": "#0c0e14",
        "voxen-surface": "#0f1117",
      },
      spacing: {
        section: "96px",
        "4px": "4px",
        "8px": "8px",
        "12px": "12px",
        "16px": "16px",
        "20px": "20px",
        "24px": "24px",
        "32px": "32px",
        "96px": "96px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        unit: "4px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "96": "96px",
      },
      borderRadius: {
        card: "12px",
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "mono-label": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        h1: ["40px", { lineHeight: "48px", fontWeight: "600" }],
        h2: ["28px", { lineHeight: "36px", fontWeight: "600" }],
        h3: ["18px", { lineHeight: "24px", fontWeight: "600" }],
        body: ["16px", { lineHeight: "24px", fontWeight: "400" }],
        label: [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg": [
          "56px",
          { lineHeight: "64px", letterSpacing: "-0.04em", fontWeight: "600" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "mono-label": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
